title: Contact Details 
author: Jimmy Wijaya
email: jimmy.dian.wijaya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first site in GitHub. I will be creating some contents about myself. 
  Keep an eye out on this page. See you soon.

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
